'use strict';
const matrices = require('./advice-matrices.json');
const DEFAULT_MODEL = process.env.OPENAI_ADVICE_MODEL || process.env.OPENAI_MODEL || 'gpt-5.5';
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_URL = 'https://api.openai.com/v1/responses';
function normSubclass(v){ return String(v || '').replace(/[^0-9]/g, ''); }
function isPlainObject(v){ return v && typeof v === 'object' && !Array.isArray(v); }
function normKey(s){ return String(s || '').toLowerCase().replace(/[^a-z0-9]/g, ''); }
function cleanText(v){ if(v===undefined||v===null) return ''; if(Array.isArray(v)) return v.map(cleanText).filter(Boolean).join('; '); if(isPlainObject(v)) return JSON.stringify(v); return String(v).replace(/\s+/g,' ').trim(); }
function looksLikeDummy(v){ const s=cleanText(v).toLowerCase(); return !s || /sample\s*\d+/.test(s) || /high risk: adverse factors/i.test(s) || /^(test|dummy|n\/a|na|null|undefined)$/.test(s); }
function flatten(input,prefix='',out={}){ if(!isPlainObject(input)) return out; for(const [k,v] of Object.entries(input)){ const key=prefix?`${prefix}.${k}`:k; if(['password','token','auth','authorization','bm_session'].includes(normKey(k))) continue; if(isPlainObject(v)) flatten(v,key,out); else if(Array.isArray(v)) out[key]=v.map(cleanText).filter(Boolean).join('; '); else if(!looksLikeDummy(v)) out[key]=cleanText(v); } return out; }
function payloadOf(assessment){ const p=assessment && assessment.form_payload && typeof assessment.form_payload==='object' ? assessment.form_payload : {}; const base=isPlainObject(p.answers)?p.answers:isPlainObject(p.formPayload)?p.formPayload:isPlainObject(p.rawSubmission)?p.rawSubmission:p; return {...flatten(base), ...(isPlainObject(p.flatAnswers)?flatten(p.flatAnswers):{})}; }
function pick(flat,names,fallback=''){ const wanted=names.map(normKey); for(const [k,v] of Object.entries(flat||{})){ const nk=normKey(k); if(wanted.includes(nk) || wanted.some(w=>nk.includes(w)||w.includes(nk))){ if(!looksLikeDummy(v)) return cleanText(v); }} return fallback; }
function matrixFor(subclass){ const code=normSubclass(subclass); const m=matrices[code]; if(!m) throw new Error(`Unsupported visa subclass for advice engine: ${code || 'unknown'}. Supported: ${Object.keys(matrices).sort().join(', ')}`); return {subclass:code, ...m}; }
function negative(v){ const s=cleanText(v).toLowerCase(); return /(no|not|none|absent|missing|refused|rejected|withdrawn|cancelled|expired|invalid|unresolved|unsure|not sure|unknown|failed|bar|condition present|adverse|criminal|overstay|breach)/i.test(s); }
function positive(v){ const s=cleanText(v).toLowerCase(); return /(yes|approved|valid|current|held|satisfied|met|granted|positive|available|competent|genuine|confirmed)/i.test(s); }
const aliasBank={invitation:['invitation','skillselect'],nomination:['nomination','state-nomination','sponsor-nomination'],skills:['skills','skills-assessment','qualification','experience'],english:['english','competent-english'],points:['points','passmark'],sponsor:['sponsor','sponsorship','employer'],relationship:['relationship','partner','spouse','defacto','marriage'],funds:['funds','financial','means-of-support'],health:['health','oshc','health-insurance'],character:['character','criminal','security'],integrity:['pic4020','integrity','bogus','false'],section48:['section48','s48'],conditions:['8503','no-further-stay','nfa-condition'],coe:['coe','enrolment','course'],genuine:['genuine','intention','temporary-stay','genuine-student'],protection:['protection','refugee','persecution','harm','claim']};
function findValue(flat, aliases){ for(const [k,v] of Object.entries(flat||{})){ const nk=normKey(k); if(aliases.map(normKey).some(a=>nk.includes(a)||a.includes(nk))) return cleanText(v); } return ''; }
function runDeterministicRules(subclass, flat){ const m=matrixFor(subclass); const findings=[], hard_fails=[], review_flags=[]; for(const [key,aliases] of Object.entries(aliasBank)){ const val=findValue(flat,aliases); if(!val) continue; const status=negative(val)?'REVIEW_REQUIRED':positive(val)?'INDICATED_SATISFIED':'UNCONFIRMED'; findings.push({criterion:key, status, observed_value:val}); if(status==='REVIEW_REQUIRED') review_flags.push(`${key}: ${val}`); }
 for(const issue of m.hard||[]){ const hit=Object.entries(aliasBank).find(([k])=>issue.toLowerCase().includes(k) || (k==='conditions'&&/8503|further stay/.test(issue.toLowerCase())) || (k==='integrity'&&/4020|integrity/.test(issue.toLowerCase()))); if(hit){ const val=findValue(flat,hit[1]); if(val && negative(val)) hard_fails.push({issue, observed_value:val, consequence:'Potential blocking criterion or validity/grant risk.'}); }}
 const risk_level=hard_fails.length?'CRITICAL':review_flags.length>=3?'HIGH':review_flags.length?'MEDIUM':'LOW'; const lodgement_position=hard_fails.length?'DO_NOT_LODGE_NOW':review_flags.length?'PROCEED_AFTER_EVIDENCE_REVIEW':'MANUAL_LEGAL_REVIEW_REQUIRED'; return {subclass:m.subclass, risk_level, lodgement_position, deterministic_findings:findings, hard_fails, review_flags}; }
function structuredFacts(assessment){ const flat=payloadOf(assessment); const subclass=normSubclass(assessment.visa_type || pick(flat,['visaType','subclass','visaSubclass'])); const m=matrixFor(subclass); return {reference:assessment.id, visa_subclass:subclass, matrix_title:m.title, matrix_source:m.source, client_email:cleanText(assessment.client_email), applicant:{name:cleanText(assessment.applicant_name)||pick(flat,['full-name','fullName','applicantName','name']), email:cleanText(assessment.applicant_email)||pick(flat,['email-address','email','applicantEmail']), citizenship:pick(flat,['country-of-citizenship','citizenship','nationality','passportCountry']), date_of_birth:pick(flat,['date-of-birth','dob','dateOfBirth'])}, matter:{selected_plan:cleanText(assessment.active_plan||assessment.selected_plan), current_location:pick(flat,['current-location','currentLocation','grant-location','location']), current_visa_status:pick(flat,['current-visa-status','currentVisaStatus','qualifying-visa-held']), family_included:pick(flat,['family-included','familyIncluded','secondaryApplicants']), stream:pick(flat,['stream','selected-stream','visa-stream','application-stream'])}, subclass_factors:{occupation:pick(flat,['occupation','nominated-occupation','anzsco','course','business','investment']), nomination:pick(flat,['nomination','state-nomination-held','nomination-current','sponsor-nomination','nomination-status']), invitation:pick(flat,['invitation-held','invitation','skillselect']), sponsor:pick(flat,['sponsor','employer','partner','proposer','sponsorship']), relationship:pick(flat,['relationship','marriage','defacto','spouse','partner-evidence']), skills:pick(flat,['skills','skills-assessment-held','qualification','work-experience','experience']), english:pick(flat,['english','competent-english','english-test-type']), points:pick(flat,['points','points-breakdown','pass-mark-met']), funds:pick(flat,['funds','financial-capacity','means-of-support']), health:pick(flat,['health','health-issues','health-insurance','oshc']), character:pick(flat,['character-security-issues','character','criminal']), integrity:pick(flat,['pic4020-integrity','pic4020','bogus','false']), visa_conditions:pick(flat,['section48-bar','8503','nfa-condition','no-further-stay','current-visa-status'])}, cleaned_answers:Object.fromEntries(Object.entries(flat).slice(0,160))}; }
function schema(){ return {type:'object',additionalProperties:false,required:['subclass','risk_level','lodgement_position','title','sections','criterion_findings','evidence_required','client_next_steps','quality_flags','disclaimer'],properties:{subclass:{type:'string',enum:Object.keys(matrices)},risk_level:{type:'string',enum:['LOW','MEDIUM','HIGH','CRITICAL']},lodgement_position:{type:'string',enum:['SUITABLE_TO_PROCEED','PROCEED_AFTER_EVIDENCE_REVIEW','DO_NOT_LODGE_NOW','INVALID_OR_NOT_AVAILABLE','MANUAL_LEGAL_REVIEW_REQUIRED']},title:{type:'string'},sections:{type:'array',minItems:7,maxItems:10,items:{type:'object',additionalProperties:false,required:['heading','body'],properties:{heading:{type:'string'},body:{type:'string'}}}},criterion_findings:{type:'array',minItems:6,maxItems:22,items:{type:'object',additionalProperties:false,required:['criterion','finding','legal_consequence','evidence_gap','recommendation'],properties:{criterion:{type:'string'},finding:{type:'string'},legal_consequence:{type:'string'},evidence_gap:{type:'string'},recommendation:{type:'string'}}}},evidence_required:{type:'array',minItems:4,maxItems:30,items:{type:'string'}},client_next_steps:{type:'array',minItems:3,maxItems:15,items:{type:'string'}},quality_flags:{type:'array',maxItems:15,items:{type:'string'}},disclaimer:{type:'string'}}}; }
function framework(m){ return [`Subclass matrix: ${m.title}`,`Knowledge source: ${m.source}`,`Streams/pathways: ${(m.streams||[]).join('; ')}`,`Validity/Schedule 1: ${(m.validity||[]).join('; ')}`,`Primary grant criteria: ${(m.primary||[]).join('; ')}`,`Secondary criteria: ${(m.secondary||[]).join('; ') || 'Not applicable'}`,`Hard fail / do not lodge triggers: ${(m.hard||[]).join('; ')}`,`Evidence required: ${(m.evidence||[]).join('; ')}`].join('\n'); }
function validateAdvice(advice, subclass, matrix){ if(!advice||typeof advice!=='object') throw new Error('GPT advice response empty/invalid.'); if(String(advice.subclass)!==String(subclass)) throw new Error('GPT advice subclass mismatch.'); if(!Array.isArray(advice.sections)||advice.sections.length<7) throw new Error('GPT advice missing sections.'); if(!Array.isArray(advice.criterion_findings)||advice.criterion_findings.length<6) throw new Error('GPT advice missing criterion findings.'); const joined=JSON.stringify(advice).toLowerCase(); for(const b of ['known issue','high risk: adverse factors','sample 1','sample 2','sample 3','as an ai']) if(joined.includes(b)) throw new Error(`GPT advice quality check failed: ${b}`); if(!joined.includes('evidence')||!joined.includes('recommend')) throw new Error('GPT advice too generic.'); return advice; }
async function callOpenAIForAdvice(facts, rules){ if(!OPENAI_API_KEY) throw new Error('OPENAI_API_KEY is required for migration-agent level GPT advice generation. Refusing to issue weak template PDF.'); const subclass=normSubclass(facts.visa_subclass); const m=matrixFor(subclass); const system=['You are drafting a preliminary migration advice letter for review/issue by Bircan Migration, a Registered Migration Agent practice in Australia.','Write in a firm, professional Registered Migration Agent advice style.','Apply the provided subclass legal matrix. Do not use a generic visa template.','Separate validity/time-of-application issues from time-of-decision/grant criteria.','Do not invent facts, dates, legislation or evidence. If a fact is missing or uncertain, say it cannot be confirmed from the questionnaire.','Do not quote regulation numbers unless supplied in the subclass matrix or facts. Prefer plain-law criterion descriptions.','Do not provide generic risk labels without legal consequence and next action.','Do not dump raw questionnaire answers.','This is preliminary advice subject to document review and current law/policy verification.'].join('\n'); const user=`Prepare structured preliminary advice for subclass ${subclass}.\n\n${framework(m)}\n\nDeterministic rule findings to treat as ground truth unless contradicted by clearer facts:\n${JSON.stringify(rules,null,2)}\n\nCleaned matter facts:\n${JSON.stringify(facts,null,2)}`; const body={model:DEFAULT_MODEL,input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:[{type:'input_text',text:user}]}],temperature:Number(process.env.OPENAI_ADVICE_TEMPERATURE||0.2),store:false,text:{format:{type:'json_schema',name:'migration_advice_letter_all_subclasses',strict:true,schema:schema()}}}; const response=await fetch(OPENAI_URL,{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(`OpenAI advice generation failed: ${data.error&&data.error.message?data.error.message:response.statusText}`); const out=data.output_text || (Array.isArray(data.output)?data.output.flatMap(o=>o.content||[]).map(c=>c.text||'').join(''):''); if(!out) throw new Error('OpenAI advice generation returned no structured text.'); return JSON.parse(out); }
async function generateMigrationAdvice(assessment){ const facts=structuredFacts(assessment); const subclass=normSubclass(facts.visa_subclass); const matrix=matrixFor(subclass); const rules=runDeterministicRules(subclass, facts.cleaned_answers||{}); const advice=await callOpenAIForAdvice(facts,rules); return {facts,rules,matrix,advice:validateAdvice(advice,subclass,matrix),model:DEFAULT_MODEL}; }
module.exports={generateMigrationAdvice,structuredFacts,validateAdvice,matrices,supportedSubclasses:()=>Object.keys(matrices).sort()};
