
const BACKEND_BASE='https://bircan-migration-backend.onrender.com';
const EXAM_SECONDS=45*60, EXAM_SIZE=20;
const PLAN_MAP={20:{attempts:20,price:'$50',title:'20 exam pack'},50:{attempts:50,price:'$100',title:'50 exam pack'},100:{attempts:100,price:'$150',title:'100 exam pack'}};
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function getAnon(){let t=localStorage.getItem('citizenshipAnonToken'); if(!t){t=(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random()); localStorage.setItem('citizenshipAnonToken',t)} return t;}
function show(el,on){if(el)el.classList.toggle('hidden',!on)}
function resultMarkup(result,title){
 const cats=Object.entries(result.categories||{}).map(([k,v])=>'<li>'+esc(k)+': '+v.correct+'/'+v.total+'</li>').join('');
 const wrong=(result.review||[]).filter(r=>!r.correct).map(r=>'<li class="wrong-review"><strong>Q'+(r.index+1)+':</strong> '+esc(r.question)+'<br><span class="muted">Your answer: '+esc(r.selectedText||'No answer selected')+'. Correct answer: '+esc(r.correctText)+'. '+esc(r.explanation)+'</span></li>').join('');
 const correct=(result.review||[]).filter(r=>r.correct).slice(0,8).map(r=>'<li class="correct-review"><strong>Q'+(r.index+1)+':</strong> '+esc(r.question)+'<br><span class="muted">Correct answer: '+esc(r.correctText)+'</span></li>').join('');
 return '<div class="result-head"><div><h3 class="result-title">'+esc(title)+'</h3><p class="muted">Correct and incorrect answers are now shown for review.</p></div><span class="result-status '+(result.passed?'pass':'fail')+'">'+(result.passed?'Pass':'Fail')+'</span></div><div class="result-grid"><div class="result-metric"><strong>'+result.score+'/20</strong><span>Overall score</span></div><div class="result-metric"><strong>'+result.valuesCorrect+'/'+result.valuesTotal+'</strong><span>Values score</span></div><div class="result-metric"><strong>'+(result.passed?'Passed':'Not passed')+'</strong><span>Outcome</span></div></div><strong>Why this result was reached</strong><ul class="reason-list">'+(result.reasons||[]).map(r=>'<li>'+esc(r)+'</li>').join('')+'</ul><strong style="display:block;margin-top:14px">Category breakdown</strong><ul class="reason-list">'+cats+'</ul>'+(wrong?'<strong style="display:block;margin-top:14px">Incorrect answers</strong><ul class="review-list">'+wrong+'</ul>':'')+(correct?'<strong style="display:block;margin-top:14px">Sample correct answers</strong><ul class="review-list">'+correct+'</ul>':'');
}
function makeExam(kind){
 const free=kind==='free';
 return {kind,examId:null,questions:[],answers:[],index:0,submitted:false,result:null,timer:null,left:EXAM_SECONDS,el: free?{
  attemptsLeft:$('[data-free-attempts-left]'),attemptsUsed:$('[data-free-attempts-used]'),score:$('[data-free-score]'),values:$('[data-free-values]'),timer:$('[data-free-timer]'),progress:$('[data-free-progress]'),category:$('[data-free-result-pill]'),question:$('[data-free-question]'),options:$('[data-free-options]'),feedback:$('[data-free-feedback]'),result:$('[data-free-result]'),mode:$('[data-free-mode-label]'),palette:$('[data-free-palette]'),start:$('#startFreeExamBtn'),prev:$('#prevFreeQuestionBtn'),next:$('#nextFreeQuestionBtn'),submit:$('#submitFreeExamBtn'),reset:$('#resetFreeExamBtn')
 }:{
  score:$('[data-score]'),timer:$('[data-timer]'),attemptsUsed:$('[data-attempts-used]'),attemptsLeft:$('[data-attempts-left]'),progress:$('[data-progress]'),category:$('[data-plan-pill]'),question:$('[data-question]'),options:$('[data-options]'),feedback:$('[data-feedback]'),result:$('[data-paid-result]'),mode:$('[data-paid-mode-label]'),palette:$('[data-paid-palette]'),start:$('#startExamBtn'),prev:$('#prevQuestionBtn'),next:$('#nextQuestionBtn'),submit:$('#submitExamBtn'),reset:$('#resetExamBtn')
 }};
}
const freeExam=makeExam('free'), paidExam=makeExam('paid'); let paidAccessToken=localStorage.getItem('citizenshipAccessToken')||''; let paidPlan=localStorage.getItem('citizenshipPaidPlan')||'';
function renderPalette(exam){if(!exam.el.palette)return; exam.el.palette.innerHTML=''; exam.questions.forEach((q,i)=>{const b=document.createElement('button'); b.type='button'; b.textContent=i+1; const answered=exam.answers[i]!==null&&exam.answers[i]!==undefined; if(exam.submitted&&exam.result){b.className='palette-btn '+(exam.result.review[i].correct?'correct':'wrong');}else{b.className='palette-btn '+(answered?'answered':'unanswered')+(i===exam.index?' current':'');} b.title=(answered?'Answered':'Not answered')+(i===exam.index?' - current question':''); b.onclick=()=>{exam.index=i; renderExam(exam);}; exam.el.palette.appendChild(b);});}
function renderExam(exam){const q=exam.questions[exam.index]; if(!q)return; exam.el.progress.textContent='Question '+(exam.index+1)+' of 20'; exam.el.category.textContent=q.isValue?'Australian values question':(q.category||'General'); exam.el.question.textContent=q.question; exam.el.options.innerHTML=''; q.options.forEach((opt,i)=>{const btn=document.createElement('button'); btn.type='button'; btn.className='option-btn'; btn.textContent=opt; if(exam.answers[exam.index]===i)btn.classList.add('selected'); if(exam.submitted&&exam.result){const rev=exam.result.review[exam.index]; if(i===rev.correctIndex)btn.classList.add('correct'); if(i===rev.selected&&i!==rev.correctIndex)btn.classList.add('wrong');} btn.onclick=()=>{if(exam.submitted)return; exam.answers[exam.index]=i; renderExam(exam);}; exam.el.options.appendChild(btn);}); const answered=exam.answers.filter(a=>a!==null&&a!==undefined).length; if(exam.kind==='free'){exam.el.score.textContent=answered+'/20'; exam.el.values.textContent=exam.questions.filter((q,i)=>q.isValue&&exam.answers[i]!==null&&exam.answers[i]!==undefined).length+'/5';} else {exam.el.score.textContent=answered+'/20';} exam.el.feedback.textContent=exam.submitted?'Review complete. Correct and incorrect answers are shown.':'Select an answer. You may go back and change answers before submitting.'; exam.el.feedback.className='feedback'; exam.el.prev.disabled=exam.index===0; exam.el.next.disabled=exam.index===exam.questions.length-1; if(exam.el.submit)exam.el.submit.disabled=exam.submitted; renderPalette(exam);}
function setButtonsInProgress(exam){show(exam.el.start,false);show(exam.el.prev,true);show(exam.el.next,true);show(exam.el.submit,true);if(exam.el.prev)exam.el.prev.disabled=true;if(exam.el.next)exam.el.next.disabled=false;if(exam.el.submit)exam.el.submit.disabled=false;if(exam.el.result)exam.el.result.classList.add('hidden');if(exam.el.mode)exam.el.mode.textContent='In progress';}
function resetButtons(exam){show(exam.el.start,true);show(exam.el.prev,false);show(exam.el.next,false);show(exam.el.submit,false);if(exam.el.prev)exam.el.prev.disabled=true;if(exam.el.next)exam.el.next.disabled=true;if(exam.el.submit)exam.el.submit.disabled=true;}
function startTimer(exam){clearInterval(exam.timer); exam.left=EXAM_SECONDS; exam.el.timer.textContent=fmt(exam.left); exam.timer=setInterval(()=>{exam.left--; exam.el.timer.textContent=fmt(exam.left); if(exam.left<=0)submitExam(exam,true).catch(e=>{exam.el.feedback.textContent=e.message; exam.el.feedback.className='feedback error'});},1000);}
async function startFree(){const r=await fetch(BACKEND_BASE+'/api/citizenship/start-free',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientToken:getAnon()})}); const d=await r.json(); if(!r.ok)throw new Error(d.error||'Free exam could not start'); Object.assign(freeExam,{examId:d.examId,questions:d.questions,answers:Array(d.questions.length).fill(null),index:0,submitted:false,result:null}); if(freeExam.el.attemptsLeft)freeExam.el.attemptsLeft.textContent=d.attempts.remaining; if(freeExam.el.attemptsUsed)freeExam.el.attemptsUsed.textContent=d.attempts.used; setButtonsInProgress(freeExam); renderExam(freeExam); startTimer(freeExam);}
async function startPaid(){if(!paidAccessToken)throw new Error('Paid access is not verified. Complete Stripe checkout first.'); const r=await fetch(BACKEND_BASE+'/api/citizenship/start-paid',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accessToken:paidAccessToken,plan:paidPlan})}); const d=await r.json(); if(!r.ok)throw new Error(d.error||'Paid exam could not start'); Object.assign(paidExam,{examId:d.examId,questions:d.questions,answers:Array(d.questions.length).fill(null),index:0,submitted:false,result:null}); updatePaidEntitlement(d.entitlement); setButtonsInProgress(paidExam); renderExam(paidExam); startTimer(paidExam);}
async function submitExam(exam,timedOut=false){if(exam.submitted)return; const unanswered=exam.answers.filter(a=>a===null||a===undefined).length; if(unanswered&&!timedOut&&!confirm('You have '+unanswered+' unanswered question(s). Submit anyway?'))return; clearInterval(exam.timer); const r=await fetch(BACKEND_BASE+'/api/citizenship/submit-exam',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({examId:exam.examId,answers:exam.answers})}); const d=await r.json(); if(!r.ok)throw new Error(d.error||'Exam could not be submitted'); exam.submitted=true; exam.result=d.result; exam.el.mode.textContent='Complete'; show(exam.el.submit,false); if(exam.el.result){exam.el.result.className='result-card '+(d.result.passed?'pass':'fail'); exam.el.result.innerHTML=resultMarkup(d.result,exam.kind==='free'?'Free practice result':'Paid mock exam result');} if(exam.kind==='free'&&d.attempts){if(exam.el.attemptsLeft)exam.el.attemptsLeft.textContent=d.attempts.remaining;if(exam.el.attemptsUsed)exam.el.attemptsUsed.textContent=d.attempts.used;} if(exam.kind==='paid'&&d.entitlement)updatePaidEntitlement(d.entitlement); renderExam(exam);}
function updatePaidEntitlement(e){if(!e)return; paidPlan=e.plan; localStorage.setItem('citizenshipPaidPlan',paidPlan); $('[data-selected-title]').textContent=(e.planLabel||PLAN_MAP[e.plan]?.title||'Paid plan')+' verified'; $('[data-selected-copy]').textContent='Payment verified. Attempts are now stored and deducted securely on the backend.'; $('[data-selected-attempts]').textContent=e.total; $('[data-selected-price]').textContent=PLAN_MAP[e.plan]?.price||''; $('[data-selected-remaining]').textContent=e.remaining; if(paidExam.el.attemptsUsed)paidExam.el.attemptsUsed.textContent=e.used; if(paidExam.el.attemptsLeft)paidExam.el.attemptsLeft.textContent=e.remaining; if(paidExam.el.mode)paidExam.el.mode.textContent='Verified'; $('#paymentNotice').innerHTML='<strong>Payment confirmed</strong> Your paid exam pack is ready.';}
$$('.select-plan-btn').forEach(btn=>btn.onclick=async e=>{e.preventDefault(); const plan=btn.dataset.plan; localStorage.setItem('citizenshipPaidPlan',plan); btn.textContent='Redirecting to Stripe...'; try{const r=await fetch(BACKEND_BASE+'/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan})}); const d=await r.json(); if(!r.ok||!d.url)throw new Error(d.error||'Checkout could not be created'); location.href=d.url;}catch(err){btn.textContent='Choose '+plan+' exams'; $('#paymentNotice').innerHTML='<strong>Stripe checkout error</strong> '+esc(err.message);}});
freeExam.el.start.onclick=()=>startFree().catch(e=>{freeExam.el.feedback.textContent=e.message;freeExam.el.feedback.className='feedback error'}); paidExam.el.start.onclick=()=>startPaid().catch(e=>{paidExam.el.feedback.textContent=e.message;paidExam.el.feedback.className='feedback error'});
[[freeExam,'free'],[paidExam,'paid']].forEach(([exam])=>{exam.el.prev.onclick=()=>{if(exam.index>0){exam.index--;renderExam(exam)}}; exam.el.next.onclick=()=>{if(exam.index<exam.questions.length-1){exam.index++;renderExam(exam)}}; exam.el.submit.onclick=()=>submitExam(exam,false).catch(e=>{exam.el.feedback.textContent=e.message;exam.el.feedback.className='feedback error'}); if(exam.el.reset)exam.el.reset.onclick=()=>{clearInterval(exam.timer); resetButtons(exam); exam.questions=[]; exam.answers=[]; exam.index=0; exam.submitted=false; exam.el.options.innerHTML=''; exam.el.palette.innerHTML=''; exam.el.result.classList.add('hidden'); exam.el.feedback.textContent='';};});
async function bootstrap(){const params=new URLSearchParams(location.search); const sessionId=params.get('session_id'); const plan=params.get('plan')||localStorage.getItem('citizenshipPaidPlan')||''; if(plan)paidPlan=plan; if(sessionId){const r=await fetch(BACKEND_BASE+'/checkout/verify-session?session_id='+encodeURIComponent(sessionId)+'&plan='+encodeURIComponent(plan)); const d=await r.json(); if(d.ok&&d.accessToken){paidAccessToken=d.accessToken; localStorage.setItem('citizenshipAccessToken',paidAccessToken); updatePaidEntitlement(d.entitlement); history.replaceState({},'',location.pathname+'?plan='+encodeURIComponent(d.plan||plan)+'#paid-exams'); setTimeout(()=>$('#paid-exams').scrollIntoView({behavior:'smooth'}),150);}else{$('#paymentNotice').innerHTML='<strong>Verification failed</strong> '+esc(d.error||'Payment could not be verified.');}} else if(paidAccessToken){try{const r=await fetch(BACKEND_BASE+'/api/citizenship/entitlement?accessToken='+encodeURIComponent(paidAccessToken)); const d=await r.json(); if(d.ok)updatePaidEntitlement(d.entitlement);}catch(_){}}}
bootstrap();
